sudo: false
dist: trusty
language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
before_install: gem install bundler -v 1.15.1
install:
  - bundle install --path vendor/bundle
script:
  - LOG_LEVEL=debug bundle exec rspec
